import type { Mechanism, MechanismKey } from "@/domain/types";

/**
 * Method-independent mechanisms.
 *
 * A mechanism describes *what changes in the person*, not which tradition the
 * technique came from. This is what lets Osora mix material from very
 * different schools without the session feeling like a patchwork.
 *
 * `servesDirections` is the engine's directional-fit table. `suitableStates`
 * and `unsuitableStates` are scored; `contraindications` are gates.
 */
export const MECHANISMS: Mechanism[] = [
  {
    key: "perceived_safety",
    name: "Perceived safety",
    description:
      "Establishing a felt sense that it is okay to settle, before anything else is asked.",
    intendedEffect:
      "Reduces guardedness so that later attention work is possible rather than effortful.",
    suitableStates: [
      { dimension: "safety", operator: "lte", value: 6, note: "Low felt safety" },
      { dimension: "overwhelm", operator: "gte", value: 5 },
      { dimension: "emotional_intensity", operator: "gte", value: 6 },
    ],
    unsuitableStates: [{ dimension: "safety", operator: "gte", value: 9 }],
    contraindications: [],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-porges-2007", "src-gilbert-2009"],
    requiredSkills: ["trauma_informed_practice"],
    recommendedSeconds: 90,
    minExposureSeconds: 40,
    maxExposureSeconds: 180,
    compatibleWith: ["sensory_grounding", "exteroceptive_orientation", "predictability", "silence"],
    incompatibleWith: [],
    servesDirections: {
      more_grounded: 0.9,
      less_overwhelmed: 1,
      calmer: 0.6,
      more_accepting: 0.4,
    },
    reviewStatus: "approved",
    version: 4,
    tags: ["foundational", "always-eligible"],
  },
  {
    key: "sensory_grounding",
    name: "Sensory grounding",
    description:
      "Directing attention to simple, verifiable sensory contact — weight, texture, temperature.",
    intendedEffect: "Anchors attention in something concrete and reduces cognitive drift.",
    suitableStates: [
      { dimension: "overwhelm", operator: "gte", value: 5 },
      { dimension: "mental_activity", operator: "gte", value: 6 },
      { dimension: "restlessness", operator: "gte", value: 5 },
    ],
    unsuitableStates: [{ dimension: "tiredness", operator: "gte", value: 9 }],
    contraindications: [],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-kabatzinn-1982"],
    requiredSkills: ["meditation_instruction"],
    recommendedSeconds: 120,
    minExposureSeconds: 45,
    maxExposureSeconds: 240,
    compatibleWith: [
      "perceived_safety",
      "exteroceptive_orientation",
      "body_awareness",
      "attention_stabilisation",
    ],
    incompatibleWith: [],
    servesDirections: {
      more_grounded: 1,
      less_overwhelmed: 0.8,
      calmer: 0.6,
      more_focused: 0.5,
    },
    reviewStatus: "approved",
    version: 5,
    tags: ["foundational", "grounding"],
  },
  {
    key: "exteroceptive_orientation",
    name: "Exteroceptive orientation",
    description:
      "Turning attention outward — to sound, light, or the shape of the room — rather than inward.",
    intendedEffect:
      "Offers a route to settling that does not require tolerating internal sensation.",
    suitableStates: [
      { dimension: "overwhelm", operator: "gte", value: 7 },
      { dimension: "emotional_intensity", operator: "gte", value: 7 },
      { dimension: "safety", operator: "lte", value: 5 },
    ],
    unsuitableStates: [{ dimension: "focus", operator: "gte", value: 8 }],
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-levine-2010"],
    requiredSkills: ["trauma_informed_practice", "somatic_practice"],
    recommendedSeconds: 90,
    minExposureSeconds: 40,
    maxExposureSeconds: 180,
    compatibleWith: ["perceived_safety", "sensory_grounding", "attentional_widening"],
    incompatibleWith: ["interoceptive_awareness"],
    servesDirections: { less_overwhelmed: 0.9, more_grounded: 0.8, more_spacious: 0.6 },
    reviewStatus: "approved",
    version: 3,
    tags: ["safety-route", "trauma-informed"],
  },
  {
    key: "extended_exhalation",
    name: "Extended exhalation",
    description: "Gently lengthening the out-breath relative to the in-breath.",
    intendedEffect: "Supports a shift toward lower physiological activation.",
    suitableStates: [
      { dimension: "stress", operator: "gte", value: 5 },
      { dimension: "physical_tension", operator: "gte", value: 5 },
      { dimension: "restlessness", operator: "gte", value: 5 },
    ],
    unsuitableStates: [{ dimension: "energy", operator: "lte", value: 2 }],
    contraindications: [
      {
        id: "ci-exhale-breathing-discomfort",
        summary: "Discomfort with breath-focused attention",
        condition: { dimension: "discomfort", operator: "gte", value: 7 },
        guidance:
          "Offer an alternative anchor. Do not instruct breath-holding, forced patterns, or counting under strain.",
        requiresSkill: "breathwork",
      },
    ],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-zaccaro-2018", "src-laborde-2022"],
    requiredSkills: ["breathwork"],
    recommendedSeconds: 150,
    minExposureSeconds: 60,
    maxExposureSeconds: 300,
    compatibleWith: ["breath_awareness", "rhythmic_entrainment", "muscle_relaxation", "body_awareness"],
    incompatibleWith: [],
    servesDirections: {
      calmer: 1,
      ready_for_sleep: 0.8,
      less_overwhelmed: 0.6,
      more_grounded: 0.5,
    },
    reviewStatus: "approved",
    version: 6,
    tags: ["breath", "down-regulation"],
  },
  {
    key: "breath_awareness",
    name: "Breath awareness",
    description: "Noticing the breath as it already is, without changing it.",
    intendedEffect: "Provides a continuously available anchor with minimal instruction.",
    suitableStates: [
      { dimension: "mental_activity", operator: "gte", value: 5 },
      { dimension: "focus", operator: "lte", value: 6 },
    ],
    unsuitableStates: [{ dimension: "discomfort", operator: "gte", value: 7 }],
    contraindications: [
      {
        id: "ci-breath-awareness-anxiety",
        summary: "Breath attention can increase activation for some people",
        condition: { dimension: "overwhelm", operator: "gte", value: 8 },
        guidance:
          "At very high overwhelm, offer an exteroceptive anchor first and make the breath optional.",
        requiresSkill: "trauma_informed_practice",
      },
    ],
    evidenceLevel: "strong",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-kabatzinn-1982", "src-goyal-2014"],
    requiredSkills: ["meditation_instruction"],
    recommendedSeconds: 150,
    minExposureSeconds: 60,
    maxExposureSeconds: 360,
    compatibleWith: ["attention_stabilisation", "extended_exhalation", "body_awareness", "silence"],
    incompatibleWith: [],
    servesDirections: {
      calmer: 0.7,
      more_focused: 0.8,
      less_mentally_busy: 0.8,
      more_grounded: 0.5,
    },
    reviewStatus: "approved",
    version: 5,
    tags: ["breath", "anchor"],
  },
  {
    key: "attention_stabilisation",
    name: "Attention stabilisation",
    description: "Repeatedly returning attention to a chosen anchor, without judgement.",
    intendedEffect: "Trains the return itself rather than sustained concentration.",
    suitableStates: [
      { dimension: "focus", operator: "lte", value: 6 },
      { dimension: "mental_activity", operator: "gte", value: 5 },
    ],
    unsuitableStates: [
      { dimension: "overwhelm", operator: "gte", value: 8 },
      { dimension: "energy", operator: "lte", value: 2 },
    ],
    contraindications: [],
    evidenceLevel: "strong",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-goyal-2014", "src-tang-2015"],
    requiredSkills: ["meditation_instruction"],
    recommendedSeconds: 180,
    minExposureSeconds: 60,
    maxExposureSeconds: 420,
    compatibleWith: ["breath_awareness", "sensory_grounding", "repetition", "silence"],
    incompatibleWith: ["attentional_widening"],
    servesDirections: { more_focused: 1, less_mentally_busy: 0.7, calmer: 0.4 },
    reviewStatus: "approved",
    version: 4,
    tags: ["attention"],
  },
  {
    key: "attentional_widening",
    name: "Attentional widening",
    description: "Letting attention open to the whole field rather than one point.",
    intendedEffect: "Creates a felt sense of room around experience.",
    suitableStates: [
      { dimension: "openness", operator: "gte", value: 5 },
      { dimension: "safety", operator: "gte", value: 6 },
    ],
    unsuitableStates: [
      { dimension: "mental_activity", operator: "gte", value: 8 },
      { dimension: "focus", operator: "lte", value: 3 },
    ],
    contraindications: [
      {
        id: "ci-widening-low-safety",
        summary: "Open awareness is destabilising when felt safety is low",
        condition: { dimension: "safety", operator: "lte", value: 4 },
        guidance: "Keep attention anchored and structured instead.",
        requiresSkill: "trauma_informed_practice",
      },
    ],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-lutz-2008"],
    requiredSkills: ["meditation_instruction"],
    recommendedSeconds: 150,
    minExposureSeconds: 60,
    maxExposureSeconds: 300,
    compatibleWith: ["silence", "acceptance", "progressive_guidance_reduction"],
    incompatibleWith: ["attention_stabilisation"],
    servesDirections: { more_spacious: 1, more_accepting: 0.6, calmer: 0.4 },
    reviewStatus: "approved",
    version: 3,
    tags: ["attention", "open-awareness"],
  },
  {
    key: "interoceptive_awareness",
    name: "Interoceptive awareness",
    description: "Noticing internal bodily signals such as heartbeat, warmth, or breath movement.",
    intendedEffect: "Builds a finer-grained sense of internal state.",
    suitableStates: [
      { dimension: "safety", operator: "gte", value: 6 },
      { dimension: "openness", operator: "gte", value: 5 },
    ],
    unsuitableStates: [{ dimension: "emotional_intensity", operator: "gte", value: 7 }],
    contraindications: [
      {
        id: "ci-intero-overwhelm",
        summary: "Interoceptive focus can amplify distress at high overwhelm",
        condition: { dimension: "overwhelm", operator: "gte", value: 7 },
        guidance: "Use exteroceptive orientation instead. This exclusion is not overridable.",
        requiresSkill: "trauma_informed_practice",
      },
      {
        id: "ci-intero-discomfort",
        summary: "Attention to internal sensation near a painful area",
        condition: { dimension: "discomfort", operator: "gte", value: 7 },
        guidance: "Route attention to a neutral region only, with pain-science review.",
        requiresSkill: "pain_science",
      },
    ],
    evidenceLevel: "preliminary",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-farb-2015"],
    requiredSkills: ["somatic_practice", "trauma_informed_practice"],
    recommendedSeconds: 150,
    minExposureSeconds: 60,
    maxExposureSeconds: 300,
    compatibleWith: ["body_awareness", "breath_awareness", "acceptance"],
    incompatibleWith: ["exteroceptive_orientation"],
    servesDirections: { more_connected: 0.8, more_grounded: 0.6, more_accepting: 0.5 },
    reviewStatus: "approved",
    version: 4,
    tags: ["body", "advanced"],
  },
  {
    key: "body_awareness",
    name: "Body awareness",
    description: "Moving attention systematically through regions of the body.",
    intendedEffect: "Distributes attention widely enough to interrupt narrow mental loops.",
    suitableStates: [
      { dimension: "physical_tension", operator: "gte", value: 4 },
      { dimension: "mental_activity", operator: "gte", value: 5 },
      { dimension: "tiredness", operator: "gte", value: 4 },
    ],
    unsuitableStates: [{ dimension: "restlessness", operator: "gte", value: 9 }],
    contraindications: [
      {
        id: "ci-body-pain",
        summary: "Systematic scanning can bring attention to a painful region",
        condition: { dimension: "discomfort", operator: "gte", value: 7 },
        guidance: "Offer an explicit route around the area, or omit the region entirely.",
        requiresSkill: "pain_science",
      },
    ],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-kabatzinn-1982", "src-goyal-2014"],
    requiredSkills: ["meditation_instruction", "somatic_practice"],
    recommendedSeconds: 240,
    minExposureSeconds: 90,
    maxExposureSeconds: 600,
    compatibleWith: ["muscle_relaxation", "extended_exhalation", "silence", "interoceptive_awareness"],
    incompatibleWith: [],
    servesDirections: {
      calmer: 0.8,
      ready_for_sleep: 0.9,
      more_grounded: 0.8,
      less_mentally_busy: 0.7,
    },
    reviewStatus: "approved",
    version: 6,
    tags: ["body", "foundational"],
  },
  {
    key: "muscle_relaxation",
    name: "Muscle relaxation",
    description: "Inviting release in specific muscle groups, sequentially.",
    intendedEffect: "Reduces held physical tension and its feedback into felt stress.",
    suitableStates: [
      { dimension: "physical_tension", operator: "gte", value: 5 },
      { dimension: "stress", operator: "gte", value: 5 },
    ],
    unsuitableStates: [{ dimension: "energy", operator: "gte", value: 9 }],
    contraindications: [],
    evidenceLevel: "strong",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-manzoni-2008"],
    requiredSkills: ["somatic_practice"],
    recommendedSeconds: 180,
    minExposureSeconds: 60,
    maxExposureSeconds: 420,
    compatibleWith: ["body_awareness", "extended_exhalation", "silence"],
    incompatibleWith: [],
    servesDirections: { calmer: 0.9, ready_for_sleep: 0.9, more_grounded: 0.5 },
    reviewStatus: "approved",
    version: 4,
    tags: ["body", "relaxation"],
  },
  {
    key: "cognitive_distancing",
    name: "Cognitive distancing",
    description: "Relating to a thought as an event in the mind rather than as a fact.",
    intendedEffect: "Loosens the grip of repetitive thinking without arguing with its content.",
    suitableStates: [
      { dimension: "rumination", operator: "gte", value: 5 },
      { dimension: "mental_activity", operator: "gte", value: 6 },
    ],
    unsuitableStates: [
      { dimension: "energy", operator: "lte", value: 3 },
      { dimension: "focus", operator: "lte", value: 3 },
    ],
    contraindications: [
      {
        id: "ci-distancing-overwhelm",
        summary: "Cognitive work requires spare capacity",
        condition: { dimension: "overwhelm", operator: "gte", value: 8 },
        guidance: "Stabilise first; cognitive framing lands poorly at high overwhelm.",
        requiresSkill: "clinical_psychology",
      },
    ],
    evidenceLevel: "strong",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-hayes-2006", "src-bernstein-2015"],
    requiredSkills: ["clinical_psychology"],
    recommendedSeconds: 150,
    minExposureSeconds: 60,
    maxExposureSeconds: 300,
    compatibleWith: ["emotional_labelling", "acceptance", "attention_stabilisation"],
    incompatibleWith: [],
    servesDirections: {
      less_mentally_busy: 1,
      more_spacious: 0.8,
      more_accepting: 0.7,
      calmer: 0.5,
    },
    reviewStatus: "approved",
    version: 5,
    tags: ["cognitive"],
  },
  {
    key: "emotional_labelling",
    name: "Emotional labelling",
    description: "Naming what is felt, in plain and unhurried language.",
    intendedEffect: "Naming appears to reduce the intensity of the felt experience.",
    suitableStates: [
      { dimension: "emotional_intensity", operator: "gte", value: 5 },
      { dimension: "safety", operator: "gte", value: 5 },
    ],
    unsuitableStates: [{ dimension: "openness", operator: "lte", value: 3 }],
    contraindications: [
      {
        id: "ci-labelling-low-safety",
        summary: "Turning toward feeling requires baseline safety",
        condition: { dimension: "safety", operator: "lte", value: 4 },
        guidance: "Establish perceived safety and orientation first.",
        requiresSkill: "trauma_informed_practice",
      },
    ],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-lieberman-2007"],
    requiredSkills: ["clinical_psychology", "trauma_informed_practice"],
    recommendedSeconds: 120,
    minExposureSeconds: 45,
    maxExposureSeconds: 240,
    compatibleWith: ["acceptance", "cognitive_distancing", "self_compassion"],
    incompatibleWith: [],
    servesDirections: { more_accepting: 0.9, less_mentally_busy: 0.5, more_connected: 0.6 },
    reviewStatus: "approved",
    version: 4,
    tags: ["emotion"],
  },
  {
    key: "acceptance",
    name: "Acceptance",
    description: "Allowing what is present to be present, without needing to change it.",
    intendedEffect: "Reduces the secondary strain of resisting an experience.",
    suitableStates: [
      { dimension: "openness", operator: "lte", value: 6 },
      { dimension: "safety", operator: "gte", value: 5 },
    ],
    unsuitableStates: [{ dimension: "overwhelm", operator: "gte", value: 8 }],
    contraindications: [],
    evidenceLevel: "strong",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-hayes-2006"],
    requiredSkills: ["clinical_psychology"],
    recommendedSeconds: 150,
    minExposureSeconds: 60,
    maxExposureSeconds: 300,
    compatibleWith: ["emotional_labelling", "attentional_widening", "self_compassion", "silence"],
    incompatibleWith: [],
    servesDirections: { more_accepting: 1, more_spacious: 0.7, calmer: 0.4 },
    reviewStatus: "approved",
    version: 4,
    tags: ["cognitive", "acceptance"],
  },
  {
    key: "self_compassion",
    name: "Self-compassion",
    description: "Meeting one's own difficulty with the warmth one would offer a friend.",
    intendedEffect: "Softens self-criticism and increases felt connectedness.",
    suitableStates: [
      { dimension: "connectedness", operator: "lte", value: 5 },
      { dimension: "emotional_intensity", operator: "gte", value: 4 },
    ],
    unsuitableStates: [{ dimension: "openness", operator: "lte", value: 2 }],
    contraindications: [
      {
        id: "ci-compassion-backdraft",
        summary: "Warmth directed inward can initially intensify difficult feeling",
        condition: { dimension: "emotional_intensity", operator: "gte", value: 8 },
        guidance:
          "Keep phrases short and neutral, and explicitly permit stopping. Requires trauma-informed review.",
        requiresSkill: "trauma_informed_practice",
      },
    ],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-neff-2013", "src-gilbert-2009"],
    requiredSkills: ["clinical_psychology", "trauma_informed_practice"],
    recommendedSeconds: 150,
    minExposureSeconds: 60,
    maxExposureSeconds: 300,
    compatibleWith: ["acceptance", "emotional_labelling", "repetition"],
    incompatibleWith: [],
    servesDirections: { more_connected: 1, more_accepting: 0.8, calmer: 0.4 },
    reviewStatus: "approved",
    version: 4,
    tags: ["emotion", "warmth"],
  },
  {
    key: "rhythmic_entrainment",
    name: "Rhythmic entrainment",
    description: "Offering a steady external rhythm for attention or breath to settle into.",
    intendedEffect: "Reduces the effort of self-regulation by externalising the pace.",
    suitableStates: [
      { dimension: "restlessness", operator: "gte", value: 5 },
      { dimension: "focus", operator: "lte", value: 5 },
    ],
    unsuitableStates: [{ dimension: "openness", operator: "lte", value: 3 }],
    contraindications: [],
    evidenceLevel: "preliminary",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-thaut-2015"],
    requiredSkills: ["music_composition", "sound_design"],
    recommendedSeconds: 150,
    minExposureSeconds: 60,
    maxExposureSeconds: 300,
    compatibleWith: ["extended_exhalation", "repetition", "predictability"],
    incompatibleWith: ["silence"],
    servesDirections: { calmer: 0.7, more_focused: 0.6, ready_for_sleep: 0.6 },
    reviewStatus: "approved",
    version: 3,
    tags: ["sound", "rhythm"],
  },
  {
    key: "imagery",
    name: "Imagery",
    description: "Evoking a scene or image that supports the intended direction.",
    intendedEffect: "Gives attention something absorbing that is not the current difficulty.",
    suitableStates: [
      { dimension: "openness", operator: "gte", value: 5 },
      { dimension: "safety", operator: "gte", value: 5 },
    ],
    unsuitableStates: [
      { dimension: "mental_activity", operator: "gte", value: 8 },
      { dimension: "focus", operator: "lte", value: 3 },
    ],
    contraindications: [
      {
        id: "ci-imagery-intrusive",
        summary: "Imagery is unpredictable when emotional intensity is high",
        condition: { dimension: "emotional_intensity", operator: "gte", value: 8 },
        guidance: "Use concrete sensory grounding instead of evocative scenes.",
        requiresSkill: "trauma_informed_practice",
      },
    ],
    evidenceLevel: "preliminary",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-holmes-2010"],
    requiredSkills: ["meditation_instruction"],
    recommendedSeconds: 180,
    minExposureSeconds: 60,
    maxExposureSeconds: 360,
    compatibleWith: ["attentional_widening", "acceptance", "silence"],
    incompatibleWith: [],
    servesDirections: { more_spacious: 0.9, calmer: 0.6, ready_for_sleep: 0.6 },
    reviewStatus: "approved",
    version: 3,
    tags: ["imagery"],
  },
  {
    key: "silence",
    name: "Silence",
    description: "Deliberate unguided time inside the session.",
    intendedEffect: "Lets whatever was set up actually take effect, without more input.",
    suitableStates: [
      { dimension: "safety", operator: "gte", value: 5 },
      { dimension: "mental_activity", operator: "lte", value: 7 },
    ],
    unsuitableStates: [
      { dimension: "rumination", operator: "gte", value: 8 },
      { dimension: "overwhelm", operator: "gte", value: 8 },
    ],
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-osora-note-silence"],
    requiredSkills: ["meditation_instruction"],
    recommendedSeconds: 120,
    minExposureSeconds: 30,
    maxExposureSeconds: 420,
    compatibleWith: ["body_awareness", "breath_awareness", "acceptance", "attentional_widening"],
    incompatibleWith: ["rhythmic_entrainment"],
    servesDirections: {
      more_spacious: 0.9,
      ready_for_sleep: 0.7,
      calmer: 0.6,
      less_mentally_busy: 0.5,
    },
    reviewStatus: "approved",
    version: 5,
    tags: ["structure", "silence"],
  },
  {
    key: "predictability",
    name: "Predictability",
    description: "Telling the person what is coming, and then doing exactly that.",
    intendedEffect: "Removes the low-level vigilance of not knowing what happens next.",
    suitableStates: [
      { dimension: "safety", operator: "lte", value: 6 },
      { dimension: "overwhelm", operator: "gte", value: 5 },
    ],
    unsuitableStates: [],
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-osora-note-structure"],
    requiredSkills: ["meditation_instruction"],
    recommendedSeconds: 45,
    minExposureSeconds: 20,
    maxExposureSeconds: 90,
    compatibleWith: ["perceived_safety", "repetition", "sensory_grounding"],
    incompatibleWith: [],
    servesDirections: { less_overwhelmed: 0.8, more_grounded: 0.6, calmer: 0.4 },
    reviewStatus: "approved",
    version: 3,
    tags: ["structure", "osora-dna"],
  },
  {
    key: "repetition",
    name: "Repetition",
    description: "Returning to the same phrase, rhythm, or instruction across the session.",
    intendedEffect: "Reduces novelty load and creates a recognisable through-line.",
    suitableStates: [
      { dimension: "mental_activity", operator: "gte", value: 5 },
      { dimension: "focus", operator: "lte", value: 6 },
    ],
    unsuitableStates: [{ dimension: "openness", operator: "gte", value: 9 }],
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-osora-note-structure"],
    requiredSkills: ["meditation_instruction"],
    recommendedSeconds: 60,
    minExposureSeconds: 20,
    maxExposureSeconds: 180,
    compatibleWith: ["attention_stabilisation", "self_compassion", "rhythmic_entrainment"],
    incompatibleWith: [],
    servesDirections: { more_focused: 0.6, calmer: 0.5, more_grounded: 0.5 },
    reviewStatus: "approved",
    version: 2,
    tags: ["structure", "osora-dna"],
  },
  {
    key: "progressive_guidance_reduction",
    name: "Progressive reduction of guidance",
    description: "Speaking less as the session goes on, until the voice steps back entirely.",
    intendedEffect: "Hands the session over to the person rather than ending it abruptly.",
    suitableStates: [{ dimension: "safety", operator: "gte", value: 5 }],
    unsuitableStates: [{ dimension: "rumination", operator: "gte", value: 8 }],
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-osora-note-structure"],
    requiredSkills: ["meditation_instruction", "voice_direction"],
    recommendedSeconds: 90,
    minExposureSeconds: 30,
    maxExposureSeconds: 240,
    compatibleWith: ["silence", "attentional_widening", "body_awareness"],
    incompatibleWith: [],
    servesDirections: { more_spacious: 0.8, ready_for_sleep: 0.8, calmer: 0.5 },
    reviewStatus: "approved",
    version: 3,
    tags: ["structure", "osora-dna"],
  },
];

export const MECHANISM_BY_KEY: Record<MechanismKey, Mechanism> = Object.fromEntries(
  MECHANISMS.map((m) => [m.key, m]),
) as Record<MechanismKey, Mechanism>;

export function mechanismName(key: MechanismKey): string {
  return MECHANISM_BY_KEY[key]?.name ?? key;
}
