import type { Intervention } from "@/domain/types";

/**
 * Concrete, reusable intervention blocks.
 *
 * `sourceTradition` records where a block came from so the team can trace
 * provenance — it is internal only and is never surfaced in the consumer
 * experience. What the listener hears is one consistent Osora language.
 *
 * `boundaryTags` is the join key for hard user boundaries: a tagged block is
 * removed from the candidate set before scoring, so it can never appear in a
 * ranking, a plan, or an LLM prompt.
 */
export const INTERVENTIONS: Intervention[] = [
  {
    key: "three-points-of-contact",
    name: "Three points of contact",
    description:
      "Noticing three places where the body meets a supporting surface, one at a time.",
    mechanisms: [
      { mechanism: "sensory_grounding", weight: 1 },
      { mechanism: "perceived_safety", weight: 0.4 },
    ],
    suitableStates: [
      { dimension: "overwhelm", operator: "gte", value: 4 },
      { dimension: "mental_activity", operator: "gte", value: 5 },
    ],
    excludedStates: [],
    targetOutcome: "Attention lands somewhere concrete within the first minute.",
    instructions:
      "Name three contact points in a fixed order: feet, seat, hands. Allow a breath between each.",
    scriptTemplate:
      "Let your attention move to where your {{contact_one}} meets what is holding it.\n\n[pause 6]\n\nAnd now {{contact_two}}.\n\n[pause 6]\n\nAnd {{contact_three}}. Nothing to change — just noticing that the contact is there.",
    minDurationSeconds: 45,
    preferredDurationSeconds: 75,
    maxDurationSeconds: 150,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 6, maxPauseSeconds: 10, pauseRatio: 0.45 },
    voiceRequirements: "Low, unhurried. No rising inflection at the end of instructions.",
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-kabatzinn-1982"],
    requiredSkills: ["meditation_instruction"],
    reviewStatus: "approved",
    familiarityGroup: "grounding_core",
    sourceTradition: "vipassana",
    boundaryTags: [],
    major: false,
    tags: ["opening", "grounding", "always-safe"],
    version: 6,
  },
  {
    key: "gentle-exhale-extension",
    name: "Gentle exhale extension",
    description: "Letting the out-breath become a little longer than the in-breath.",
    mechanisms: [
      { mechanism: "extended_exhalation", weight: 1 },
      { mechanism: "breath_awareness", weight: 0.5 },
    ],
    suitableStates: [
      { dimension: "stress", operator: "gte", value: 5 },
      { dimension: "physical_tension", operator: "gte", value: 4 },
    ],
    excludedStates: [{ dimension: "discomfort", operator: "gte", value: 7 }],
    targetOutcome: "A measurable drop in felt activation without effortful breathing.",
    instructions:
      "Invite, never instruct, a longer exhale. No counting, no holding, no target ratio.",
    scriptTemplate:
      "See if the out-breath can become just a little longer than the in-breath.\n\n[pause 8]\n\nNot forcing it — more like letting it lengthen on its own.\n\n[pause 10]",
    minDurationSeconds: 60,
    preferredDurationSeconds: 120,
    maxDurationSeconds: 240,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 9, maxPauseSeconds: 14, pauseRatio: 0.55 },
    voiceRequirements: "Exhale-paced delivery. The voice should model the slowing.",
    soundRequirements: "Ambient bed only, no rhythmic pulse that competes with breath.",
    silenceCompatible: true,
    contraindications: [
      {
        id: "ci-exhale-forcing",
        summary: "Must not become a breath-control exercise",
        condition: null,
        guidance:
          "No counts, no ratios, no retention. If the script implies a target pattern, breathwork review is required.",
        requiresSkill: "breathwork",
      },
    ],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-zaccaro-2018", "src-laborde-2022"],
    requiredSkills: ["breathwork"],
    reviewStatus: "approved",
    familiarityGroup: "breath_core",
    sourceTradition: "breathwork",
    boundaryTags: [],
    major: false,
    tags: ["breath", "down-regulation"],
    version: 7,
  },
  {
    key: "slow-breathing-rhythm",
    name: "Slow breathing rhythm",
    description: "Following a steady external breathing pace carried by sound.",
    mechanisms: [
      { mechanism: "rhythmic_entrainment", weight: 1 },
      { mechanism: "extended_exhalation", weight: 0.6 },
    ],
    suitableStates: [
      { dimension: "restlessness", operator: "gte", value: 5 },
      { dimension: "focus", operator: "lte", value: 5 },
    ],
    excludedStates: [{ dimension: "discomfort", operator: "gte", value: 7 }],
    targetOutcome: "Breath settles into a slower pace without the person tracking it themselves.",
    instructions: "Sound carries the pace; the voice only names the arrival and the release.",
    scriptTemplate:
      "There's a slow rise and fall underneath the words now. Let your breath find it — or not.\n\n[pause 12]\n\nIn with the rise.\n\n[pause 6]\n\nAnd out, a little longer.",
    minDurationSeconds: 90,
    preferredDurationSeconds: 150,
    maxDurationSeconds: 300,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 10, maxPauseSeconds: 16, pauseRatio: 0.6 },
    voiceRequirements: "Must sit behind the rhythmic bed, not on top of it.",
    soundRequirements: "Slow rhythmic bed at 5–6 cycles per minute. No transients.",
    silenceCompatible: false,
    contraindications: [],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-zaccaro-2018", "src-thaut-2015"],
    requiredSkills: ["breathwork", "sound_design"],
    reviewStatus: "approved",
    familiarityGroup: "breath_core",
    sourceTradition: "breathwork",
    boundaryTags: ["strong_breath_manipulation"],
    major: true,
    tags: ["breath", "sound-led"],
    version: 4,
  },
  {
    key: "feet-to-head-scan",
    name: "Feet-to-head scan",
    description: "Moving attention slowly upward through the body in named regions.",
    mechanisms: [
      { mechanism: "body_awareness", weight: 1 },
      { mechanism: "muscle_relaxation", weight: 0.5 },
    ],
    suitableStates: [
      { dimension: "physical_tension", operator: "gte", value: 4 },
      { dimension: "tiredness", operator: "gte", value: 4 },
    ],
    excludedStates: [{ dimension: "discomfort", operator: "gte", value: 7 }],
    targetOutcome: "Attention distributed across the body rather than held in one loop.",
    instructions:
      "Fixed region order, same every time — this is part of the Osora familiar anchor. Never rush a region.",
    scriptTemplate:
      "Starting at your feet.\n\n[pause 10]\n\nThe lower legs.\n\n[pause 10]\n\n{{region_sequence}}\n\nAnd all the way up, until attention rests somewhere behind the eyes.",
    minDurationSeconds: 120,
    preferredDurationSeconds: 240,
    maxDurationSeconds: 480,
    guidanceDensity: "moderate",
    pausePattern: { afterInstructionSeconds: 10, maxPauseSeconds: 15, pauseRatio: 0.5 },
    voiceRequirements: "Even pacing. No emphasis shifts between regions.",
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [
      {
        id: "ci-scan-pain-region",
        summary: "The fixed sequence will reach a painful region",
        condition: { dimension: "discomfort", operator: "gte", value: 6 },
        guidance:
          "Use the neutral-region variant, which routes attention around the area. Requires pain-science review.",
        requiresSkill: "pain_science",
      },
    ],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-kabatzinn-1982"],
    requiredSkills: ["meditation_instruction", "somatic_practice"],
    reviewStatus: "approved",
    familiarityGroup: "body_core",
    sourceTradition: "yoga_nidra",
    boundaryTags: ["body_scanning"],
    major: true,
    tags: ["body", "core"],
    version: 8,
  },
  {
    key: "neutral-region-check",
    name: "Neutral region check",
    description: "Finding a part of the body that feels neutral or easy, and resting there.",
    mechanisms: [
      { mechanism: "body_awareness", weight: 0.8 },
      { mechanism: "perceived_safety", weight: 0.7 },
    ],
    suitableStates: [
      { dimension: "discomfort", operator: "gte", value: 5 },
      { dimension: "safety", operator: "lte", value: 6 },
    ],
    excludedStates: [],
    targetOutcome: "A safe internal reference point that does not require tolerating difficulty.",
    instructions:
      "Never name the difficult area. The person chooses the neutral region; the script only offers the search.",
    scriptTemplate:
      "Somewhere in your body there's a place that feels neutral. Maybe an elbow, maybe the back of a hand.\n\n[pause 12]\n\nLet attention rest there for a while.\n\n[pause 15]",
    minDurationSeconds: 60,
    preferredDurationSeconds: 120,
    maxDurationSeconds: 240,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 12, maxPauseSeconds: 18, pauseRatio: 0.6 },
    voiceRequirements: "Quiet and permissive.",
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-levine-2010"],
    requiredSkills: ["trauma_informed_practice", "pain_science"],
    reviewStatus: "approved",
    familiarityGroup: "body_core",
    sourceTradition: "somatic_practice",
    boundaryTags: [],
    major: false,
    tags: ["body", "trauma-informed", "pain-safe"],
    version: 5,
  },
  {
    key: "progressive-release",
    name: "Progressive release",
    description: "Inviting release group by group, without first tensing.",
    mechanisms: [
      { mechanism: "muscle_relaxation", weight: 1 },
      { mechanism: "body_awareness", weight: 0.5 },
    ],
    suitableStates: [
      { dimension: "physical_tension", operator: "gte", value: 5 },
      { dimension: "stress", operator: "gte", value: 5 },
    ],
    excludedStates: [],
    targetOutcome: "Reduced held tension, especially jaw, shoulders and hands.",
    instructions: "Release-only variant. No tense-and-release cycling in evening sessions.",
    scriptTemplate:
      "Your jaw. See if it can be a little looser than it is.\n\n[pause 8]\n\nThe shoulders — let them drop, even slightly.\n\n[pause 8]\n\nThe hands. Nothing to hold.",
    minDurationSeconds: 60,
    preferredDurationSeconds: 150,
    maxDurationSeconds: 300,
    guidanceDensity: "moderate",
    pausePattern: { afterInstructionSeconds: 8, maxPauseSeconds: 12, pauseRatio: 0.45 },
    voiceRequirements: "Descending intonation on each release.",
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "strong",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-manzoni-2008"],
    requiredSkills: ["somatic_practice"],
    reviewStatus: "approved",
    familiarityGroup: "body_core",
    sourceTradition: "somatic_practice",
    boundaryTags: [],
    major: false,
    tags: ["body", "relaxation"],
    version: 5,
  },
  {
    key: "thought-as-event",
    name: "Thought as an event",
    description: "Noticing a thought as something the mind produced, and leaving it unsolved.",
    mechanisms: [
      { mechanism: "cognitive_distancing", weight: 1 },
      { mechanism: "acceptance", weight: 0.4 },
    ],
    suitableStates: [
      { dimension: "rumination", operator: "gte", value: 5 },
      { dimension: "mental_activity", operator: "gte", value: 6 },
    ],
    excludedStates: [{ dimension: "overwhelm", operator: "gte", value: 8 }],
    targetOutcome: "A repeating thought loses some of its pull without being argued with.",
    instructions:
      "Never suggest the thought is wrong or irrational. The move is one of relationship, not content.",
    scriptTemplate:
      "If a thought is circling, you don't have to finish it.\n\n[pause 10]\n\nYou could notice it the way you'd notice a sound outside — something happening, not something to solve.\n\n[pause 12]",
    minDurationSeconds: 75,
    preferredDurationSeconds: 150,
    maxDurationSeconds: 300,
    guidanceDensity: "moderate",
    pausePattern: { afterInstructionSeconds: 11, maxPauseSeconds: 16, pauseRatio: 0.5 },
    voiceRequirements: "Matter-of-fact rather than soothing.",
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "strong",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-hayes-2006", "src-bernstein-2015"],
    requiredSkills: ["clinical_psychology"],
    reviewStatus: "approved",
    familiarityGroup: "cognitive_core",
    sourceTradition: "act",
    boundaryTags: [],
    major: true,
    tags: ["cognitive"],
    version: 6,
  },
  {
    key: "name-the-feeling",
    name: "Name the feeling",
    description: "Finding one plain word for what is present right now.",
    mechanisms: [
      { mechanism: "emotional_labelling", weight: 1 },
      { mechanism: "acceptance", weight: 0.5 },
    ],
    suitableStates: [
      { dimension: "emotional_intensity", operator: "gte", value: 5 },
      { dimension: "safety", operator: "gte", value: 5 },
    ],
    excludedStates: [{ dimension: "safety", operator: "lte", value: 4 }],
    targetOutcome: "The feeling becomes something observed rather than something inhabited.",
    instructions:
      "One word only. Never suggest the word. Always permit 'I don't know' as a complete answer.",
    scriptTemplate:
      "If there were one word for what's here — just one — what would it be?\n\n[pause 14]\n\nNo need to be right about it. And if nothing comes, that's an answer too.",
    minDurationSeconds: 60,
    preferredDurationSeconds: 120,
    maxDurationSeconds: 210,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 14, maxPauseSeconds: 20, pauseRatio: 0.6 },
    voiceRequirements: "Unhurried, with a genuine pause after the question.",
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [
      {
        id: "ci-naming-exposure",
        summary: "Turning toward feeling is a form of exposure",
        condition: { dimension: "emotional_intensity", operator: "gte", value: 8 },
        guidance: "Requires trauma-informed review and an explicit permission to stop.",
        requiresSkill: "trauma_informed_practice",
      },
    ],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-lieberman-2007"],
    requiredSkills: ["clinical_psychology", "trauma_informed_practice"],
    reviewStatus: "approved",
    familiarityGroup: "cognitive_core",
    sourceTradition: "act",
    boundaryTags: ["emotional_exposure"],
    major: true,
    tags: ["emotion"],
    version: 5,
  },
  {
    key: "self-compassion-phrase",
    name: "Self-compassion phrase",
    description: "A short phrase repeated a few times, offered rather than instructed.",
    mechanisms: [
      { mechanism: "self_compassion", weight: 1 },
      { mechanism: "repetition", weight: 0.6 },
    ],
    suitableStates: [
      { dimension: "connectedness", operator: "lte", value: 5 },
      { dimension: "emotional_intensity", operator: "gte", value: 4 },
    ],
    excludedStates: [{ dimension: "openness", operator: "lte", value: 2 }],
    targetOutcome: "A warmer internal tone that persists past the end of the session.",
    instructions:
      "Phrases stay short and concrete. Nothing aspirational, nothing that could read as a promise.",
    scriptTemplate:
      "You might try a phrase. Something like: {{phrase}}.\n\n[pause 10]\n\nAgain, if it fits.\n\n[pause 12]\n\nAnd if it doesn't fit, let it go. It isn't required.",
    minDurationSeconds: 60,
    preferredDurationSeconds: 120,
    maxDurationSeconds: 240,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 11, maxPauseSeconds: 15, pauseRatio: 0.55 },
    voiceRequirements: "Warm without becoming performative.",
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [
      {
        id: "ci-compassion-backdraft-block",
        summary: "Warmth can intensify difficulty before it eases it",
        condition: { dimension: "emotional_intensity", operator: "gte", value: 8 },
        guidance: "Requires trauma-informed review.",
        requiresSkill: "trauma_informed_practice",
      },
    ],
    evidenceLevel: "moderate",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-neff-2013"],
    requiredSkills: ["clinical_psychology", "trauma_informed_practice"],
    reviewStatus: "approved",
    familiarityGroup: "compassion_core",
    sourceTradition: "act",
    boundaryTags: [],
    major: true,
    tags: ["emotion", "warmth"],
    version: 5,
  },
  {
    key: "outward-listening",
    name: "Outward listening",
    description: "Letting attention rest on the furthest sound that can be heard.",
    mechanisms: [
      { mechanism: "exteroceptive_orientation", weight: 1 },
      { mechanism: "attentional_widening", weight: 0.5 },
    ],
    suitableStates: [
      { dimension: "overwhelm", operator: "gte", value: 6 },
      { dimension: "emotional_intensity", operator: "gte", value: 6 },
    ],
    excludedStates: [],
    targetOutcome: "Settling that does not require any contact with internal sensation.",
    instructions:
      "Always available as the safe alternative when interoceptive routes are excluded.",
    scriptTemplate:
      "Let your hearing go out past the room.\n\n[pause 12]\n\nThe furthest sound you can find — just resting there.\n\n[pause 15]",
    minDurationSeconds: 60,
    preferredDurationSeconds: 120,
    maxDurationSeconds: 240,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 13, maxPauseSeconds: 18, pauseRatio: 0.6 },
    voiceRequirements: "Quiet, close-mic, no reverb tail.",
    soundRequirements: "Very low ambient bed or none at all.",
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-levine-2010"],
    requiredSkills: ["trauma_informed_practice"],
    reviewStatus: "approved",
    familiarityGroup: "grounding_core",
    sourceTradition: "somatic_practice",
    boundaryTags: [],
    major: false,
    tags: ["grounding", "trauma-informed", "always-safe"],
    version: 4,
  },
  {
    key: "inside-to-outside-shift",
    name: "Inside-to-outside shift",
    description: "Deliberately moving attention from internal sensation to the surroundings.",
    mechanisms: [
      { mechanism: "exteroceptive_orientation", weight: 0.9 },
      { mechanism: "attentional_widening", weight: 0.6 },
    ],
    suitableStates: [
      { dimension: "rumination", operator: "gte", value: 6 },
      { dimension: "overwhelm", operator: "gte", value: 5 },
    ],
    excludedStates: [],
    targetOutcome: "Breaks a closed internal loop by changing the direction of attention.",
    instructions: "The shift itself is the intervention — name it explicitly as a move.",
    scriptTemplate:
      "For a moment, everything was pointed inward.\n\n[pause 6]\n\nNow let it turn around. The room. The air. Whatever is out there.\n\n[pause 12]",
    minDurationSeconds: 45,
    preferredDurationSeconds: 90,
    maxDurationSeconds: 180,
    guidanceDensity: "moderate",
    pausePattern: { afterInstructionSeconds: 9, maxPauseSeconds: 14, pauseRatio: 0.5 },
    voiceRequirements: null,
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "preliminary",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-levine-2010"],
    requiredSkills: ["somatic_practice"],
    reviewStatus: "approved",
    familiarityGroup: "grounding_core",
    sourceTradition: "feldenkrais",
    boundaryTags: [],
    major: false,
    tags: ["transition", "grounding"],
    version: 3,
  },
  {
    key: "wide-landscape-image",
    name: "Wide landscape image",
    description: "Evoking an open natural scene with room in every direction.",
    mechanisms: [
      { mechanism: "imagery", weight: 1 },
      { mechanism: "attentional_widening", weight: 0.5 },
    ],
    suitableStates: [
      { dimension: "openness", operator: "gte", value: 5 },
      { dimension: "overwhelm", operator: "gte", value: 4 },
    ],
    excludedStates: [{ dimension: "emotional_intensity", operator: "gte", value: 8 }],
    targetOutcome: "A felt sense of space that carries past the image itself.",
    instructions:
      "Neutral natural scenes only, from the approved theme list. No people, no narrative.",
    scriptTemplate:
      "Somewhere wide. {{scene}}. Not a memory in particular — just the sense of room.\n\n[pause 15]\n\nAnd the space in it. That's the part to stay with.\n\n[pause 12]",
    minDurationSeconds: 90,
    preferredDurationSeconds: 180,
    maxDurationSeconds: 300,
    guidanceDensity: "moderate",
    pausePattern: { afterInstructionSeconds: 13, maxPauseSeconds: 18, pauseRatio: 0.5 },
    voiceRequirements: "Descriptive but unhurried; avoid a storytelling cadence.",
    soundRequirements: "Wide, diffuse ambience with no identifiable events.",
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "preliminary",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-holmes-2010"],
    requiredSkills: ["meditation_instruction"],
    reviewStatus: "approved",
    familiarityGroup: "imagery_extended",
    sourceTradition: "hypnosis",
    boundaryTags: ["visualisation"],
    major: true,
    tags: ["imagery"],
    version: 4,
  },
  {
    key: "ambient-passage",
    name: "Ambient passage",
    description: "A stretch of sound with no voice at all.",
    mechanisms: [
      { mechanism: "silence", weight: 0.7 },
      { mechanism: "rhythmic_entrainment", weight: 0.4 },
    ],
    suitableStates: [{ dimension: "mental_activity", operator: "lte", value: 8 }],
    excludedStates: [],
    targetOutcome: "Time for the preceding block to take effect without further input.",
    instructions:
      "Not silence — a held ambient bed. Use when full silence would feel like an absence.",
    scriptTemplate: "[sound_only {{seconds}}]",
    minDurationSeconds: 45,
    preferredDurationSeconds: 120,
    maxDurationSeconds: 300,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 0, maxPauseSeconds: 0, pauseRatio: 1 },
    voiceRequirements: null,
    soundRequirements: "Continuous bed, no transients, no loop seam.",
    silenceCompatible: false,
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-osora-note-silence"],
    requiredSkills: ["sound_design"],
    reviewStatus: "approved",
    familiarityGroup: "sound_extended",
    sourceTradition: "music_psychology",
    boundaryTags: [],
    major: false,
    tags: ["sound", "structure"],
    version: 3,
  },
  {
    key: "lightly-held-silence",
    name: "Lightly held silence",
    description: "Unguided time, with one brief re-anchor in the middle.",
    mechanisms: [
      { mechanism: "silence", weight: 1 },
      { mechanism: "progressive_guidance_reduction", weight: 0.6 },
    ],
    suitableStates: [{ dimension: "safety", operator: "gte", value: 5 }],
    excludedStates: [{ dimension: "rumination", operator: "gte", value: 8 }],
    targetOutcome: "The person carries the session themselves for a while.",
    instructions:
      "Exactly one re-anchor, placed at the midpoint. Never fill silence with reassurance.",
    scriptTemplate:
      "[silence {{first_half}}]\n\nStill here.\n\n[silence {{second_half}}]",
    minDurationSeconds: 60,
    preferredDurationSeconds: 150,
    maxDurationSeconds: 420,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 0, maxPauseSeconds: 210, pauseRatio: 0.95 },
    voiceRequirements: "The single re-anchor is quieter than everything before it.",
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-osora-note-silence"],
    requiredSkills: ["meditation_instruction"],
    reviewStatus: "approved",
    familiarityGroup: "silence_core",
    sourceTradition: "zen",
    boundaryTags: [],
    major: false,
    tags: ["silence", "structure", "osora-dna"],
    version: 5,
  },
  {
    key: "return-without-comment",
    name: "Return without comment",
    description: "Noticing that attention wandered, and returning without evaluating it.",
    mechanisms: [
      { mechanism: "attention_stabilisation", weight: 1 },
      { mechanism: "acceptance", weight: 0.4 },
    ],
    suitableStates: [
      { dimension: "focus", operator: "lte", value: 6 },
      { dimension: "mental_activity", operator: "gte", value: 5 },
    ],
    excludedStates: [],
    targetOutcome: "The return becomes automatic rather than a moment of self-criticism.",
    instructions: "Never frame wandering as failure. The return is the practice.",
    scriptTemplate:
      "If you notice you've drifted, that noticing is the whole thing.\n\n[pause 10]\n\nCome back. No comment needed.\n\n[pause 14]",
    minDurationSeconds: 60,
    preferredDurationSeconds: 150,
    maxDurationSeconds: 360,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 12, maxPauseSeconds: 18, pauseRatio: 0.6 },
    voiceRequirements: null,
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "strong",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-tang-2015"],
    requiredSkills: ["meditation_instruction"],
    reviewStatus: "approved",
    familiarityGroup: "grounding_core",
    sourceTradition: "vipassana",
    boundaryTags: [],
    major: false,
    tags: ["attention", "core"],
    version: 5,
  },
  {
    key: "what-is-already-here",
    name: "What is already here",
    description: "Allowing the present experience to be as it is for a stretch of time.",
    mechanisms: [
      { mechanism: "acceptance", weight: 1 },
      { mechanism: "attentional_widening", weight: 0.5 },
    ],
    suitableStates: [
      { dimension: "openness", operator: "lte", value: 6 },
      { dimension: "safety", operator: "gte", value: 5 },
    ],
    excludedStates: [{ dimension: "overwhelm", operator: "gte", value: 8 }],
    targetOutcome: "Less energy spent resisting the current state.",
    instructions: "No implication that acceptance produces change. That would be a claim.",
    scriptTemplate:
      "Whatever is here right now — it's already here.\n\n[pause 12]\n\nYou don't have to do anything with it for the next minute.\n\n[pause 18]",
    minDurationSeconds: 75,
    preferredDurationSeconds: 150,
    maxDurationSeconds: 300,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 14, maxPauseSeconds: 20, pauseRatio: 0.6 },
    voiceRequirements: null,
    soundRequirements: null,
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "strong",
    knowledgeKind: "scientific_evidence",
    supportingSourceIds: ["src-hayes-2006"],
    requiredSkills: ["clinical_psychology"],
    reviewStatus: "approved",
    familiarityGroup: "cognitive_core",
    sourceTradition: "act",
    boundaryTags: [],
    major: false,
    tags: ["acceptance"],
    version: 4,
  },
  {
    key: "what-happens-next",
    name: "What happens next",
    description: "Stating the shape of the session before it begins.",
    mechanisms: [
      { mechanism: "predictability", weight: 1 },
      { mechanism: "perceived_safety", weight: 0.6 },
    ],
    suitableStates: [
      { dimension: "safety", operator: "lte", value: 7 },
      { dimension: "overwhelm", operator: "gte", value: 4 },
    ],
    excludedStates: [],
    targetOutcome: "No part of the session arrives as a surprise.",
    instructions:
      "Must accurately describe the session that follows. A mismatch here is a blocking rule failure.",
    scriptTemplate:
      "Here's what this is: about {{minutes}} minutes. {{shape}}. Then quiet at the end. Nothing you need to prepare for.",
    minDurationSeconds: 20,
    preferredDurationSeconds: 40,
    maxDurationSeconds: 75,
    guidanceDensity: "moderate",
    pausePattern: { afterInstructionSeconds: 3, maxPauseSeconds: 5, pauseRatio: 0.2 },
    voiceRequirements: "Plain and slightly more spoken than the rest of the session.",
    soundRequirements: null,
    silenceCompatible: false,
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-osora-note-structure"],
    requiredSkills: ["meditation_instruction"],
    reviewStatus: "approved",
    familiarityGroup: "grounding_core",
    sourceTradition: "osora_original",
    boundaryTags: [],
    major: false,
    tags: ["opening", "osora-dna", "always-safe"],
    version: 6,
  },
  {
    key: "stepping-back-close",
    name: "Stepping back close",
    description: "The voice speaks less and less until it stops.",
    mechanisms: [
      { mechanism: "progressive_guidance_reduction", weight: 1 },
      { mechanism: "silence", weight: 0.5 },
    ],
    suitableStates: [],
    excludedStates: [],
    targetOutcome: "The session ends without a felt cut.",
    instructions:
      "Three statements, each shorter than the last, then nothing. Part of the stable Osora closing.",
    scriptTemplate:
      "Whenever you're ready — no rush at all.\n\n[pause 12]\n\nThis stays available.\n\n[pause 15]\n\nTake your time.",
    minDurationSeconds: 45,
    preferredDurationSeconds: 75,
    maxDurationSeconds: 150,
    guidanceDensity: "sparse",
    pausePattern: { afterInstructionSeconds: 13, maxPauseSeconds: 20, pauseRatio: 0.65 },
    voiceRequirements: "Each line quieter and slower than the one before.",
    soundRequirements: "Bed fades out across the final 20 seconds.",
    silenceCompatible: true,
    contraindications: [],
    evidenceLevel: "expert_consensus",
    knowledgeKind: "expert_opinion",
    supportingSourceIds: ["src-osora-note-structure"],
    requiredSkills: ["meditation_instruction", "voice_direction"],
    reviewStatus: "approved",
    familiarityGroup: "silence_core",
    sourceTradition: "osora_original",
    boundaryTags: [],
    major: false,
    tags: ["closing", "osora-dna", "always-safe"],
    version: 7,
  },
];

export const INTERVENTION_BY_KEY: Record<string, Intervention> = Object.fromEntries(
  INTERVENTIONS.map((i) => [i.key, i]),
);

/** Blocks that stay eligible under every gate — the engine's fallback core. */
export const SAFE_CORE_INTERVENTION_KEYS = [
  "what-happens-next",
  "three-points-of-contact",
  "outward-listening",
  "return-without-comment",
  "stepping-back-close",
];
